### ISSUE TITLE
LAB02 is old and not match with English version

### ISSUE THREAD

**Issue by lettucebo** [MicrosoftLearning/DP-060ZH-Migrating-your-Database-to-Cosmos-DB#1]
LAB02 is **unusable** due to old instruction, the English version is correct

**Comment by LuongNguyen0906** [comment]
Hi Lettucebo, 

As I have checked, LAB02 is not updated. please can you check and provide me some details?

Thanks.

**Comment by lettucebo** [comment]
Hi

The LAB02 compare to the English version

The first is that the VM image(MongoDB Community) state in the ZH version is no longer exist

and the Repo URL is also wrong

In EN version the step already be changing to install mongodb by themselves

**Comment by LuongNguyen0906** [comment]
issue was fixed.
